server:
  port: 8089
  servlet:
    context-path: /ttdemo
  tomcat:
    uri-encoding: utf-8

spring:
  thymeleaf: #编码格式
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  devtools: #热部署生效
    restart:
      enabled: true
  mvc: # 静态文件请求匹配方式
    static-path-pattern: /static/**
  resources: # 修改默认的静态寻址资源目录 多个使用逗号分隔
    static-locations: classpath:/static/
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: true #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动会使用默认数据源.
      datasource:
        master:
          username: root
          password: root
          url: jdbc:mysql://localhost:3306/mytestdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
        hz:
          username: root
          password: root
          url: jdbc:mysql://localhost:3306/mytestdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 10000 # 连接超时时间（毫秒）


#旧版
#  server.port=8081
#  server.servlet.context-path=/ttdemo
#  server.tomcat.uri-encoding=utf-8
#  #spring.thymeleaf.prefix: classpath:/templates/
#  #spring.thymeleaf.suffix=.html
#  #编码格式
#  spring.thymeleaf.encoding=utf-8
#  spring.thymeleaf.mode=LEGACYHTML5
#  spring.thymeleaf.cache=false
#
#  #热部署生效
#  spring.devtools.restart.enabled=true
#  # 静态文件请求匹配方式
#  spring.mvc.static-path-pattern=/static/**
##spring.mvc.static-path-pattern=/**
## 修改默认的静态寻址资源目录 多个使用逗号分隔
#spring.resources.static-locations: classpath:/static/
##spring.mvc.view.prefix=/page/
##spring.mvc.view.suffix=.jsp
##mysql
#  spring.datasource.url=jdbc:mysql://localhost:3306/mytestdb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#  spring.datasource.username=root
#  spring.datasource.password=root
#  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#  spring.datasource.max-idle=10
#  spring.datasource.max-wait=100
#  spring.datasource.min-idle=5
#  spring.datasource.initial-size=5
#
#  spring.datasource.dynamic
#
#  #mybatis-plus
#  #指明mapper.xml扫描位置(classpath* 代表编译后类文件根目录)
#  #mybatis-plus.mapper-locations=classpath:/mapper/*Mapper.xml
#  #指明实体扫描(多个package用逗号或者分号分隔)
#  #mybatis-plus.typeAliasesPackage=com.cn.restyle.entity
#  #显示sql日志 TRACE，DEBUG，INFO，WARN，ERROR，FATAL，OFF
#  #logging.level.root=TRACE
#  logging.level.com.springboott.ttdemo.dao=debug
#
#  ####################### Redis config #######################
#  # Redis数据库索引（默认为0）
#  spring.redis.database=0
#  # Redis服务器地址
#  spring.redis.host=127.0.0.1
#  # Redis服务器连接端口
#  spring.redis.port=6379
#  # Redis服务器连接密码（默认为空）
#  spring.redis.password=
#  # 连接池最大连接数（使用负值表示没有限制）
#  spring.redis.jedis.pool.max-active=8
#  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  spring.redis.jedis.pool.max-wait=-1
#  # 连接池中的最大空闲连接
#  spring.redis.jedis.pool.max-idle=8
#  # 连接池中的最小空闲连接
#  spring.redis.jedis.pool.min-idle=0
#  # 连接超时时间（毫秒）
#  spring.redis.timeout=10000
#  ########################### end ###########################
#
#  #Spring Security
#  spring.security.user.name=admin
#  spring.security.user.password=admin

